address_descriptors = false
author = "Themefisher"
copyright = "www.spacemarbella.com"
custom_script = ""
description = "Marbella Luxury Beachfront Apartments and Villas For Sale"
email = "demo@email.com"
favicon = "images/favicon.png"
google_tag_manager = ""
image = "images/logo.png"
location = ""
logo = "images/logo4.png"
logo_text = "Dunique Marbella"
logo_width = "150px"
navbar_fixed = false
phone = ""
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
social = []
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = true
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
